version: "3.8"
services:
  backend:
    image: docker-registry.setera.com/my-backend-django:${BACKENDTAG}
    build:
      context: ../../my-setera-BACKEND
      dockerfile: Dockerfile.prod
    platform: linux/amd64
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      - db
      - elasticsearch
    networks:
      setera-nw:
    env_file:
      - ./.env
    command: sh -c "ls && python /app/manage.py makemigrations && python /app/manage.py migrate && python /app/manage.py runserver 0.0.0.0:8000"