version: '3.8'

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASS}
    ports:
      - "9200:9200"
    networks:
      - setera-nw
    env_file:
      - ./.env
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata: